name: VM Deployment test
on: [workflow_dispatch]

env: 
  RESOURCE_GROUP_NAME: DevOps-ToolsV2
  LOCATION: eastus
  MANAGED_IDENTITY_NAME: devOps-ToolsVm-identityV2
  KEY_VAULT_NAME: DevOps-gdf-Kv7

permissions:
  contents: read
  id-token: write
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
        - name: Deploy VM template and parameters
          run: |
            az deployment group create \
              --name 'vmDeployment' \
              --resource-group 'DevOps-ToolsV2' \
              --template-file './avm/res/compute/virtual-machine/devops-vm.bicep' \
              --parameters @./avm/res/compute/virtual-machine/main.parameters.json \
              --debug

