name: Testing Key Vault Parameters file.

on: [workflow_dispatch]

env: 
  RESOURCE_GROUP_NAME: DevOps-ToolsV2
  LOCATION: eastus
  MANAGED_IDENTITY_NAME: devOps-ToolsVm-identityV2

permissions:
  contents: read
  id-token: write

jobs:
  deploy-KV:
    name: Deploy Key Vault using Bicep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show Azure CLI version
        run: az --version    

      - name: Validate Key Vault deployment
        run: |
          az deployment group validate \
            --resource-group 'DevOps-ToolsV2' \
            --template-file './avm/res/key-vault/vault/devops-kv2.bicep' \
            --parameters @avm/res/key-vault/vault/devops-kv2.parameters.json \
            --debug

      - name: Deploy Key Vault using BICEP
        run: |
          az deployment group create \
            --name 'kvDeployment' \
            --resource-group 'DevOps-ToolsV2' \
            --template-file './avm/res/key-vault/vault/devops-kv2.bicep' \
            --parameters @avm/res/key-vault/vault/devops-kv2.parameters.json \
            --only-show-errors  
