name: Infra and DevOps VM deployment using CLI
on: [workflow_dispatch]

env: 
  RESOURCE_GROUP_NAME: DevOps-ToolsV2
  LOCATION: eastus
  MANAGED_IDENTITY_NAME: devOps-ToolsVm-identityV2
permissions:
  contents: read
  id-token: write
jobs:
      
    deploy-KV:
      name: Deploy Key Vault using Bicep
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
        - name: Get Managed Identity Object ID (CLI)
          id: get-mi
          run: |
            objectId=$(az identity show \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --name ${{ env.MANAGED_IDENTITY_NAME }} \
              --query principalId \
              --output tsv)

            echo "objectId=$objectId" >> $GITHUB_OUTPUT
        - name: Deploy Key Vault using BICEP
          run: |
            az deployment group create \
              --name deploy-kv-module \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --template-file ./avm/res/key-vault/vault/devops-kv.bicep \
              --parameters vmMiPrincipalId=${{ steps.get-mi.outputs.objectId }} \
              --only-show-errors          
    