name: Infra and DevOps VM deployment using CLI
on: [workflow_dispatch]

permissions:
  contents: read
  id-token: write
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: azure/login@v1
          with:
            client-id: '2535f38e-9d86-42dd-a415-8f388e5282fb'
            tenant-id: '577e5b12-eac6-4389-bac2-cfab1a261cef'
            subscription-id: '58a4a8cd-3b3b-4fcc-ad44-d7bf8c3df844'
        

        - name: Deploy Bicep template to subscription
          run: |
            az deployment sub create \
              --name deploy-rg-module \
              --location eastus \
              --template-file ./avm/res/resources/resource-group/main-rg.bicep \
              --only-show-errors