name: Deploy Storage Infrastructure
on: [workflow_dispatch]

env:
  STORAGE_ACCOUNT_NAME: 'devopsgdftestv3'
  STORAGE_ACCOUNT_PE_IP: '10.0.0.6'
  MANAGED_IDENTITY_NAME: 'devOps-ToolsVm-identityV2'
  RESOURCE_GROUP_NAME: 'DevOps-ToolsV2'

permissions:
  contents: read
  id-token: write
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
        - name: Get Managed Identity principalId and set as environment variable
          id: get-mi
          run: |
            MI_NAME="${{ env.MANAGED_IDENTITY_NAME }}"
            RG_NAME="${{ env.RESOURCE_GROUP_NAME }}"

            PRINCIPAL_ID=$(az identity show --name "$MI_NAME" --resource-group "$RG_NAME" --query 'principalId' -o tsv)

            echo "PRINCIPAL_ID=$PRINCIPAL_ID" >> $GITHUB_ENV     
        - name: Deploy Storage Account
          run: |
            az deployment group create \
              --name 'storageDeployment' \
              --resource-group 'DevOps-ToolsV2' \
              --parameters \
                strname=$STORAGE_ACCOUNT_NAME \
                strPeIpAddress=$STORAGE_ACCOUNT_PE_IP \
                managedIdentityPrincipalId=$PRINCIPAL_ID \
              --template-file './avm/res/storage/storage-account/devops-str.bicep' \
              --debug

        - name: Deploy Storage Account Private DNS Zone
          run: |
            az deployment group create \
              --name 'storageDeploymentprivateDns' \
              --resource-group 'DevOps-ToolsV2' \
              --template-file './avm/res/network/private-dns-zone/devops-str-pe-dns.bicep' \
              --parameters \
                strname=$STORAGE_ACCOUNT_NAME \
                strPeIpAddress=$STORAGE_ACCOUNT_PE_IP \
              --debug              

