name: Testing Key Vault Deployment using CLI

on: [workflow_dispatch]

env: 
  RESOURCE_GROUP_NAME: DevOps-ToolsV2
  LOCATION: eastus
  MANAGED_IDENTITY_NAME: devOps-ToolsVm-identityV2

permissions:
  contents: read
  id-token: write

jobs:
  deploy-KV:
    name: Deploy Key Vault using Bicep
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Key Vault parameter file
        run: |
          cat <<EOF > kv.parameters.json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "secrets": {
      "value": [
        {
          "name": "DevOps-Vm-Secretv2",
          "value": "N3xtStp1saKyV@ult!",
          "tags": {
            "created-by": "GitHub Actions",
            "created-on": "18-06-2025",
            "kv-purpose": "Secret for DevOps VM"
          },
          "attributes": {
            "enabled": true
          }
        }
      ]
    },
    "roleAssignments": {
      "value": [
        {
          "principalId": "8f9f7624-eb16-46f7-aaef-79eb06c286db",
          "roleDefinitionIdOrName": "Key Vault Secrets User",
          "description": "DevOps VM Identity",
          "principalType": "ServicePrincipal"
        },
        {
          "principalId": "75e8c793-8646-411a-b342-7a1a4c53620d",
          "roleDefinitionIdOrName": "Key Vault Administrator",
          "description": "Gabriel's User Identity",
          "principalType": "User"
        }
      ]
    },
    "vmMiPrincipalId": {
      "value": "8f9f7624-eb16-46f7-aaef-79eb06c286db"
    }
  }
}
EOF

      - name: Deploy Key Vault using BICEP
        run: |
          az deployment group create \
            --name kvDeployment \
            --resource-group $RESOURCE_GROUP_NAME \
            --template-file ./avm/res/key-vault/vault/devops-kv2.bicep \
            --only-show-errors \
            --parameters @kv.parameters.json
