name: Testing Key Vault Deployment using CLI
on: [workflow_dispatch]
env: 
  RESOURCE_GROUP_NAME: DevOps-ToolsV2
  LOCATION: eastus
  MANAGED_IDENTITY_NAME: devOps-ToolsVm-identityV2
permissions:
  contents: read
  id-token: write
jobs:
      
    deploy-KV:
      name: Deploy Key Vault using Bicep
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        - name: Deploy Key Vault using BICEP
          run: |
            az deployment group create \
              --name kvDeployment \
              --resource-group $RESOURCE_GROUP_NAME \
              --template-file ./avm/res/key-vault/vault/devops-kv2.bicep \
              --only-show-errors \
              --parameters \
                secrets='[
                  {
                    "name": "DevOps-Vm-Secretv2",
                    "value": "N3xtStp1saKyV@ult!",
                    "tags": {
                      "created-by": "Gabriel",
                      "created-on": "2025-06-18",
                      "kv-purpose": "Secret for DevOps VM"
                    },
                    "attributes": {
                      "enabled": true
                    }
                  }
                ]' \
                roleAssignments='[
                  {
                    "roleDefinitionName": "Key Vault Secrets User",
                    "principalId": "8f9f7624-eb16-46f7-aaef-79eb06c286db",
                    "description": "DevOps VM Identity.",
                    "principalType": "ServicePrincipal"
                  },
                  {
                    "roleDefinitionName": "Key Vault Administrator",
                    "principalId": "75e8c793-8646-411a-b342-7a1a4c53620d",
                      "description": "Gabriel's User Identity.",
                  "principalType": "User"
                  }
                ]' \
                vmMiPrincipalId='8f9f7624-eb16-46f7-aaef-79eb06c286db'
          