name: Heredoc Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Write JSON file
        run: |
          cat <<EOF > out.json
{
"foo": "bar"
}
EOF

      - name: show contents
        run: cat out.json